# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: node:latest
      options: --network mynet 
      env:
        name: kamal
        age: 56
        salary: nothing
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: file listing after checkout
        run: |
          pwd
          ls -ltr

      # Runs a single command using the runners shell
      - name: show bridge network
        run: docker network ls
      - name: Run a one-line script
        run: echo Hello, world!
      - name: create a bridge network
        run: |
          docker network create -d bridge mynet
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          df 
          docker version
          docker ps -a
      - name: running another container in step
        uses: docker://node:latest
        with:
          enterypoint: ls
          args: " -ltr /bin"
      - name: finding docker processes
        uses: docker://node:latest
        with:
          enterypoint: ps
          args: " -aef"

