name: testing workflow
on: [push]
jobs:
  first_job:
    name: testing job
    runs-on: ubuntu-latest
    steps:
       - name: printing ubuntu version 
         run: uname -a
       - name: checking  free memory
         run: free
       - name: listing
         run: ls -ltr /
       - name: interface
         run: |
           ls -ltr /
           ifconfig -a
      